/**
 * @fileoverview Country data organized by regions for use in signup and settings forms.
 * Provides a comprehensive list of countries with their IDs and regional groupings.
 * 
 * @typedef {Object} Country
 * @property {string} name - Country name
 * @property {string} id - Country identifier
 * 
 * @typedef {Object.<string, Country[]>} CountryData
 * @property {Country[]} "Popular Regions" - Frequently selected countries
 * @property {Country[]} "Middle East & North Africa" - MENA region countries
 * @property {Country[]} "Asia Pacific" - APAC region countries
 * @property {Country[]} "Europe" - European countries
 * @property {Country[]} "Americas" - North and South American countries
 * @property {Country[]} "Rest of World" - All other countries
 */

/** @type {CountryData} */
export const COUNTRIES = {
  "Popular Regions": [
    { name: "United States", id: "233" },
    { name: "Australia", id: "14" },
    { name: "United Kingdom", id: "232" },
    { name: "Canada", id: "40" }
  ],

  "Middle East & North Africa": [
    { name: "Algeria", id: "3" },
    { name: "Bahrain", id: "20" },
    { name: "Egypt", id: "63" },
    { name: "Iran", id: "103" },
    { name: "Iraq", id: "104" },
    { name: "Israel", id: "107" },
    { name: "Jordan", id: "112" },
    { name: "Kuwait", id: "118" },
    { name: "Lebanon", id: "122" },
    { name: "Libya", id: "125" },
    { name: "Morocco", id: "149" },
    { name: "Oman", id: "166" },
    { name: "Palestine", id: "169" },
    { name: "Qatar", id: "179" },
    { name: "Saudi Arabia", id: "193" },
    { name: "Syria", id: "213" },
    { name: "Tunisia", id: "224" },
    { name: "Turkey", id: "225" },
    { name: "United Arab Emirates", id: "231" },
    { name: "Yemen", id: "244" }
  ],

  "Asia Pacific": [
    { name: "China", id: "42" },
    { name: "Japan", id: "110" },
    { name: "South Korea", id: "117" },
    { name: "India", id: "101" },
    { name: "Indonesia", id: "102" },
    { name: "Malaysia", id: "133" },
    { name: "Philippines", id: "174" },
    { name: "Singapore", id: "198" },
    { name: "Taiwan", id: "214" },
    { name: "Thailand", id: "217" },
    { name: "Vietnam", id: "240" }
  ],

  "Europe": [
    { name: "Austria", id: "12" },
    { name: "Belgium", id: "22" },
    { name: "Denmark", id: "58" },
    { name: "Finland", id: "73" },
    { name: "France", id: "74" },
    { name: "Germany", id: "81" },
    { name: "Greece", id: "85" },
    { name: "Ireland", id: "105" },
    { name: "Italy", id: "108" },
    { name: "Netherlands", id: "155" },
    { name: "Norway", id: "165" },
    { name: "Poland", id: "176" },
    { name: "Portugal", id: "177" },
    { name: "Spain", id: "205" },
    { name: "Sweden", id: "211" },
    { name: "Switzerland", id: "212" }
  ],

  "Americas": [
    { name: "Argentina", id: "11" },
    { name: "Brazil", id: "31" },
    { name: "Chile", id: "45" },
    { name: "Colombia", id: "48" },
    { name: "Mexico", id: "142" },
    { name: "Peru", id: "173" },
    { name: "Venezuela", id: "238" }
  ],

  "Rest of World": [
    { name: "Afghanistan", id: "2" },
    { name: "Åland Islands", id: "1" },
    { name: "Albania", id: "4" },
    { name: "American Samoa", id: "5" },
    { name: "Andorra", id: "8" },
    { name: "Angola", id: "9" },
    { name: "Anguilla", id: "10" },
    { name: "Antarctica", id: "6" },
    { name: "Antigua And Barbuda", id: "7" },
    { name: "Armenia", id: "15" },
    { name: "Aruba", id: "13" },
    { name: "Azerbaijan", id: "16" },
    { name: "Bahamas", id: "18" },
    { name: "Bangladesh", id: "19" },
    { name: "Barbados", id: "17" },
    { name: "Belarus", id: "21" },
    { name: "Belize", id: "24" },
    { name: "Benin", id: "23" },
    { name: "Bermuda", id: "25" },
    { name: "Bhutan", id: "26" },
    { name: "Bolivia", id: "28" },
    { name: "Bosnia And Herzegovina", id: "30" },
    { name: "Botswana", id: "29" },
    { name: "Bouvet Island", id: "27" },
    { name: "British Indian Ocean Territory", id: "33" },
    { name: "Brunei Darussalam", id: "34" },
    { name: "Bulgaria", id: "35" },
    { name: "Burkina Faso", id: "32" },
    { name: "Burundi", id: "36" },
    { name: "Cambodia", id: "38" },
    { name: "Cameroon", id: "39" },
    { name: "Cape Verde", id: "37" },
    { name: "Caribbean Netherlands", id: "247" },
    { name: "Cayman Islands", id: "41" },
    { name: "Central African Republic", id: "43" },
    { name: "Chad", id: "44" },
    { name: "Christmas Island", id: "46" },
    { name: "Cocos (Keeling) Islands", id: "49" },
    { name: "Comoros", id: "50" },
    { name: "Congo", id: "47" },
    { name: "Congo", id: "51" },
    { name: "Cook Islands", id: "53" },
    { name: "Costa Rica", id: "55" },
    { name: "Cote Divoire", id: "52" },
    { name: "Croatia", id: "54" },
    { name: "Cuba", id: "56" },
    { name: "Curaçao", id: "249" },
    { name: "Cyprus", id: "57" },
    { name: "Czech Republic", id: "60" },
    { name: "Djibouti", id: "59" },
    { name: "Dominica", id: "61" },
    { name: "Dominican Republic", id: "62" },
    { name: "Ecuador", id: "65" },
    { name: "El Salvador", id: "64" },
    { name: "Equatorial Guinea", id: "66" },
    { name: "Eritrea", id: "68" },
    { name: "Estonia", id: "69" },
    { name: "Ethiopia", id: "67" },
    { name: "Falkland Islands", id: "70" },
    { name: "Faroe Islands", id: "71" },
    { name: "Fiji", id: "72" },
    { name: "French Guiana", id: "75" },
    { name: "French Polynesia", id: "76" },
    { name: "French Southern Territories", id: "77" },
    { name: "Gabon", id: "78" },
    { name: "Gambia", id: "79" },
    { name: "Georgia", id: "80" },
    { name: "Ghana", id: "82" },
    { name: "Gibraltar", id: "83" },
    { name: "Greenland", id: "84" },
    { name: "Grenada", id: "86" },
    { name: "Guadeloupe", id: "87" },
    { name: "Guam", id: "88" },
    { name: "Guatemala", id: "90" },
    { name: "Guernsey", id: "89" },
    { name: "Guinea", id: "91" },
    { name: "Guinea-Bissau", id: "92" },
    { name: "Guyana", id: "93" },
    { name: "Haiti", id: "94" },
    { name: "Heard Island And Mcdonald Islands", id: "95" },
    { name: "Holy See (Vatican City State)", id: "96" },
    { name: "Honduras", id: "97" },
    { name: "Hong Kong", id: "98" },
    { name: "Hungary", id: "99" },
    { name: "Iceland", id: "100" },
    { name: "Isle Of Man", id: "106" },
    { name: "Jamaica", id: "109" },
    { name: "Jersey", id: "111" },
    { name: "Kazakhstan", id: "113" },
    { name: "Kenya", id: "114" },
    { name: "Kiribati", id: "115" },
    { name: "Korea, Democratic Peoples Republic Of", id: "116" },
    { name: "Kyrgyzstan", id: "119" },
    { name: "Lao Peoples Democratic Republic", id: "120" },
    { name: "Latvia", id: "121" },
    { name: "Lesotho", id: "123" },
    { name: "Liberia", id: "124" },
    { name: "Liechtenstein", id: "126" },
    { name: "Lithuania", id: "127" },
    { name: "Luxembourg", id: "128" },
    { name: "Macao", id: "129" },
    { name: "Macedonia", id: "130" },
    { name: "Madagascar", id: "131" },
    { name: "Malawi", id: "132" },
    { name: "Maldives", id: "134" },
    { name: "Mali", id: "135" },
    { name: "Malta", id: "136" },
    { name: "Marshall Islands", id: "137" },
    { name: "Martinique", id: "138" },
    { name: "Mauritania", id: "139" },
    { name: "Mauritius", id: "140" },
    { name: "Mayotte", id: "141" },
    { name: "Micronesia", id: "143" },
    { name: "Moldova", id: "144" },
    { name: "Monaco", id: "145" },
    { name: "Mongolia", id: "146" },
    { name: "Montenegro", id: "147" },
    { name: "Montserrat", id: "148" },
    { name: "Mozambique", id: "150" },
    { name: "Myanmar", id: "151" },
    { name: "Namibia", id: "152" },
    { name: "Nauru", id: "153" },
    { name: "Nepal", id: "154" },
    { name: "Netherlands Antilles", id: "156" },
    { name: "New Caledonia", id: "157" },
    { name: "New Zealand", id: "158" },
    { name: "Nicaragua", id: "159" },
    { name: "Niger", id: "160" },
    { name: "Nigeria", id: "161" },
    { name: "Niue", id: "162" },
    { name: "Norfolk Island", id: "163" },
    { name: "Northern Mariana Islands", id: "164" },
    { name: "Pakistan", id: "167" },
    { name: "Palau", id: "168" },
    { name: "Palestinian Territory", id: "169" },
    { name: "Panama", id: "170" },
    { name: "Papua New Guinea", id: "171" },
    { name: "Paraguay", id: "172" },
    { name: "Pitcairn", id: "175" },
    { name: "Puerto Rico", id: "178" },
    { name: "Réunion", id: "180" },
    { name: "Romania", id: "181" },
    { name: "Russian Federation", id: "182" },
    { name: "Rwanda", id: "183" },
    { name: "Saint Barthélemy", id: "184" },
    { name: "Saint Helena", id: "185" },
    { name: "Saint Lucia", id: "186" },
    { name: "Saint Martin", id: "187" },
    { name: "Saint Pierre And Miquelon", id: "188" },
    { name: "Saint Vincent And The Grenadines", id: "189" },
    { name: "Samoa", id: "190" },
    { name: "San Marino", id: "191" },
    { name: "Sao Tome And Principe", id: "192" },
    { name: "Seychelles", id: "196" },
    { name: "Sierra Leone", id: "197" },
    { name: "Sint Maarten", id: "250" },
    { name: "Slovakia", id: "199" },
    { name: "Slovenia", id: "200" },
    { name: "Solomon Islands", id: "201" },
    { name: "Somalia", id: "202" },
    { name: "South Africa", id: "203" },
    { name: "South Georgia And The South Sandwich Islands", id: "204" },
    { name: "Sri Lanka", id: "206" },
    { name: "Sudan", id: "207" },
    { name: "Suriname", id: "208" },
    { name: "Svalbard And Jan Mayen", id: "209" },
    { name: "Swaziland", id: "210" },
    { name: "Tajikistan", id: "215" },
    { name: "Tanzania", id: "216" },
    { name: "Timor-Leste", id: "218" },
    { name: "Togo", id: "219" },
    { name: "Tokelau", id: "220" },
    { name: "Tonga", id: "221" },
    { name: "Trinidad And Tobago", id: "222" },
    { name: "Tts And Nevis", id: "223" },
    { name: "Turkmenistan", id: "226" },
    { name: "Turks And Caicos Islands", id: "227" },
    { name: "Tuvalu", id: "228" },
    { name: "Uganda", id: "229" },
    { name: "Ukraine", id: "230" },
    { name: "United States Minor Outlying Islands", id: "234" },
    { name: "Uruguay", id: "235" },
    { name: "Uzbekistan", id: "236" },
    { name: "Vanuatu", id: "237" },
    { name: "Virgin Islands", id: "239" },
    { name: "Virgin Islands, U.S.", id: "241" },
    { name: "Wallis And Futuna", id: "242" },
    { name: "Western Sahara", id: "243" },
    { name: "Zambia", id: "245" },
    { name: "Zimbabwe", id: "246" }
  ]
}; 