/**
 * @fileoverview AWS Amplify configuration file.
 * Contains AWS Cognito user pool configuration and authentication settings.
 * This file is automatically generated by AWS Amplify and should not be edited manually.
 */

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

/**
 * @typedef {Object} AwsAmplifyConfig
 * @property {string} aws_project_region - AWS region for the project
 * @property {string} aws_cognito_region - AWS region for Cognito service
 * @property {string} aws_user_pools_id - Cognito user pool ID
 * @property {string} aws_user_pools_web_client_id - Cognito web client ID
 * @property {Object} oauth - OAuth configuration settings
 * @property {Array<string>} aws_cognito_username_attributes - Username attributes configuration
 * @property {Array<string>} aws_cognito_social_providers - Social provider integration settings
 * @property {Array<string>} aws_cognito_signup_attributes - Required attributes for signup
 * @property {string} aws_cognito_mfa_configuration - MFA configuration setting
 * @property {Array<string>} aws_cognito_mfa_types - Supported MFA types
 * @property {Object} aws_cognito_password_protection_settings - Password policy settings
 * @property {Array<string>} aws_cognito_verification_mechanisms - Verification method settings
 */

/**
 * AWS Amplify configuration object
 * Contains all necessary settings for AWS services integration
 * @type {AwsAmplifyConfig}
 */
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_llVFNwrzo",
    "aws_user_pools_web_client_id": "18bi6aqe52e0ctu1hfoeceglg8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "EMAIL",
        "GIVEN_NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;
